apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  releaseName: metallb
  values:
    controller:
      tolerations:
        - key: role
          value: infra
      nodeSelector:
        role: infra
    speaker:
      tolerations:
        - key: role
          value: infra
      nodeSelector:
        role: infra
    existingConfigMap: metallb-config