apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: flux-system
spec:
  values:
    nfsProvisioner:
      tolerations:
      - key: "dedicated"
        value: "infra"
        effect: "NoSchedule"
      nodeSelector:
        role: infra