apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../_base/

patchesStrategicMerge:
- helmrelease-openebs.yaml
- helmrelease-ingress-nginx.yaml
- helmrelease-metrics-server.yaml