apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  storageNamespace: metallb-system
  targetNamespace: metallb-system
  chart:
    spec:
      chart: metallb
      sourceRef:
        kind: HelmRepository
        name: metallb
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 1m0s