apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  releaseName: metrics-server
  storageNamespace: kube-system
  targetNamespace: kube-system
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 1m0s
  values: {}